Repository thoth-station/ps-cv, pull requests merged in 2021-07, with the labels that each got.

#4 included all the requirements for the build of images
  .aicoe-ci.yaml
  .s2i/bin/assemble
  .s2i/bin/run
  .s2i/environment
  .thoth.yaml
  OWNERS
  OWNERS_ALIASES
  app.py
  overlays/ps-cv-ocr/Dockerfile
  overlays/ps-cv-ocr/Pipfile
  overlays/ps-cv-ocr/Pipfile.lock
  overlays/ps-cv-pytorch/Dockerfile
  overlays/ps-cv-pytorch/Pipfile
  overlays/ps-cv-pytorch/Pipfile.lock
  overlays/ps-cv-tensorflow/Dockerfile
  overlays/ps-cv-tensorflow/Pipfile
  overlays/ps-cv-tensorflow/Pipfile.lock
  template/version.py
Labels: approved, size/XXL

#6 Last updates before release
  README.rst
  overlays/ps-cv-ocr/Pipfile
  overlays/ps-cv-ocr/Pipfile.lock
  overlays/ps-cv-pytorch/Pipfile
  overlays/ps-cv-pytorch/Pipfile.lock
  overlays/ps-cv-tensorflow/Pipfile
  overlays/ps-cv-tensorflow/Pipfile.lock
  template/__init__.py
  template/version.py
Labels: size/XXL

#11 update the latest base image and fixed eol issue
  overlays/ps-cv-ocr/Dockerfile
  overlays/ps-cv-pytorch/Dockerfile
  overlays/ps-cv-tensorflow/Dockerfile
Labels: approved, size/S

#14 Adjust link to image
  README.rst
Labels: approved, size/XS

#15 Add note on binaries
  README.rst
Labels: approved, size/XS

#17 Fix Pillow upstream issue, adding pillow = '>8.3.0'
  overlays/ps-cv-pytorch/Pipfile
  overlays/ps-cv-pytorch/Pipfile.lock
Labels: approved, size/L

#22 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: bot, size/S
